# Introduction

Autonomous aerial vehicles and robotics are broadly used to provide human assistance on dangerous or complex tasks. Fields such as oil, mining, wildfire extinguishing, and precision farming are requiring more and more robotic involvement nowadays. To better accomplish the duties’ requirements, an autonomous navigation system is essential for the robots or drones to safely execute the work with minimal human control. In this project, an integration of the obstacle detection and trajectory plan has been implemented as the start point for the autonomous navigation system, before future integration on robot’s hardware. 

One of the main algorithms used in this project is the Rapid-exploring random tree (RRT) algorithm for path planning. Initially brought up by Steven M. LaVell and James J. Kuffner Jr [@rrt], the RRT algorithm could efficiently search nonconvex and high-dimensional spaces by constructing space-filling tree from samples drawn randomly in the search space and inherent grows towards large unsearched areas. The algorithm has been broadly discussed and implemented in education materials for robotics such as Python Robotics [@pythonRobotics]. Many variants and improvements for motion planning have been studied and implemented based on this algorithm. There are also comparison researches on improving the RRT algorithms [@rrtCompare]. With all these variants and improvements, the original RRT algorithm holds its tidy and simplicity which is good to be used as a start point. With original RRT algorithm, a tree will be created through adding the new nodes. The next new points of the tree is generated based on the direction to random point, selected step size and whether is on the obstacle. In this project, this original RRT algorithm has been implemented as object-oriented with MATLAB. 

Intel RealSense Camera D400 series is a stereo vision depth camera system [@realSenseD400]. The small physical size and integrated camera SDK provide flexibility on wide range of products including drones, robots, virtual reality, PC peripherals and home surveillance. Works have been done for image processing with RealSense Camera. For example, Chang utilized the OpenCV DNN object detection package within RealSense Camera to outline the obstacles in RGB content in real-time [@rscvdnn]. To better utilize the depth information, Song and Xiao implemented depth maps for object detection and designed a 3D detector to overcome the difficulties for recognition based on rendering hundreds of viewpoints of a CAD model to obtain synthetic depth maps [@slidingShapes]. In this project, Intel’s RealSense Depth Camera D435i has been used for object detection because of its handy size, ease of integration with cross-platform open source Intel RealSense SDK application and stereo depth camera which designed to maintain its calibration throughout lifetime. 

In the following sections of this report, detailed implementation process and discussion on the results will be described. For algorithm implementation, there will be explanations on the generation of an RRT tree for trajectory plan, identificaiton of the obstacle with the depth video file from RealSense camera, measurement analysis of the camera and the integration of the image processing with the trajectory plan. And in the section after, detailed assessment of the work including error source, advantages and disadvantages, and future steps for improvements will be discussed.


